### ISSUE TITLE
`spin gdb` failing with file not found error

### ISSUE THREAD

**Issue by adrinjalali** [scientific-python/spin#236]
I tested with 0.11 and 0.12, and I get this error:

```sh
(numpy) 
~/Projects/gh/me/numpy on  unique-cpp! ⌚ 16:09:25
$ spin gdb /tmp/1.py          
Invoking `build` prior to invoking gdb:
$ /home/adrin/micromamba/envs/numpy/bin/python3 vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/adrin/micromamba/envs/numpy/bin/ninja -C /home/adrin/Projects/gh/me/numpy/build
ninja: Entering directory `/home/adrin/Projects/gh/me/numpy/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /home/adrin/micromamba/envs/numpy/bin/python3 vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/home/adrin/Projects/gh/me/numpy/build-install/usr/lib/python3.12/site-packages"
$ gdb -ex 'set detach-on-fork on' --args /home/adrin/micromamba/envs/numpy/bin/python3 /tmp/1.py

Traceback (most recent call last):
  File "<frozen os>", line 580, in execvp
  File "<frozen os>", line 622, in _execvpe
  File "<frozen os>", line 613, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory

An internal error has occurred. Please file a bug report at

  https://github.com/scientific-python/spin

including the above traceback and the following information:

  spin: 0.12, package: numpy

Aborting.
(numpy) 
~/Projects/gh/me/numpy on  unique-cpp! ⌚ 16:09:30
$ which python
/home/adrin/micromamba/envs/numpy/bin/python
(numpy) 
~/Projects/gh/me/numpy on  unique-cpp! ⌚ 16:11:35
$ ls /tmp/1.py
/tmp/1.py
```

I'm trying to debug a segfault, and as the log shows, both `python` and `/tmp/1.py` exist. So not sure what's the issue here.

**Comment by adrinjalali** [comment]
scratch that. It was `gdb` which was missing (new machine). Still, the error message could mention that maybe?

**Comment by stefanv** [comment]
We definitely want to give intuitive errors for all such behavior. Let's leave this open and I'll propose a PR.

**Comment by stefanv** [comment]
Please see https://github.com/scientific-python/spin/pull/237
